# Colors to include in shell scripts
color_off='\e[0m'       # Text Reset
black='\e[0;30m'        # Black
red='\e[0;31m'          # Red
green='\e[0;32m'        # Green
yellow='\e[0;33m'       # Yellow
blue='\e[0;34m'         # Blue
purple='\e[0;35m'       # Purple
cyan='\e[0;36m'         # Cyan
white='\e[0;37m'        # Intense White
iblack='\e[0;90m'       # Intense Black
ired='\e[0;91m'         # Intense Red
igreen='\e[0;92m'       # Intense Green
iyellow='\e[0;93m'      # Intense Yellow
iblue='\e[0;94m'        # Intense Blue
ipurple='\e[0;95m'      # Intense Purple
icyan='\e[0;96m'        # Intense Cyan
iwhite='\e[0;97m'       # Intense White