#!/bin/bash
#
# Install dotfiles

DOTFILES_ROOT=`pwd`

set -e

# Format output
info () {
	printf " [ \033[00;34m..\033[0m ] $1"
}

user () {
	printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
	echo ''
	exit
}

# Helper functions
link_files () {
	ln -s $1 $2
	success "linked $1 to $2"
}

# Work to be done
symlink bash_profile
symlink bin

# Let's go


echo ''
echo ' All installed!'