#!/bin/bash
#
# Install dotfiles

# Set dotfiles_root, used in other dotfile scripts
dotfiles_root=`pwd`

sed -i "" -e "7s,[^=]*$,$dotfiles_root," $dotfiles_root/symlinks/bash_profile.symlink

# Include dependencies
source $dotfiles_root/inc/output.inc

# Abort script if any error occurs
set -e

# Helper functions
create_link () {
	if [ -L $2 ] || [ -f $2 ]
	then
		print_info "remove $2"
		rm $2
	elif [ -d $2 ]
	then
		print_info "remove $2"
		rmdir $2
	fi

	ln -s $1 $2
	print_success "linked $1 to $2"
}

# Let's go!

# [0] Start and prompt for personal information
print_prompt "Dotfiles will be installed to $dotfiles_root. Go ahead? [yes/no]"
read confirm

if [[ $confirm != 'yes' ]]
then
	fail "aborted"
fi

print_prompt "Please enter your full name"
read name
echo -e "[user]" >> $dotfiles_root/config
echo -e "\tname = $name" >> $dotfiles_root/config

print_prompt "Please enter your email address"
read email
echo -e "\tnemail = $email" >> $dotfiles_root/config

print_success "Set name to $name"
print_success "Set email to $email"

# [1] Symlink symlink files
create_link $dotfiles_root/symlinks/bash_profile.symlink $HOME/.bash_profile
create_link $dotfiles_root/symlinks/inputrc.symlink $HOME/.inputrc
create_link $dotfiles_root/symlinks/vimrc.symlink $HOME/.vimrc
create_link $dotfiles_root/symlinks/gitconfig.symlink $HOME/.gitconfig

# [2] Symlink Applications
create_link /Applications/Sublime Text 2 app/Contents/SharedSupport/bin/subl /usr/local/bin/

# [3] Add name and Email Address to your global git config
sed -i "" -e "4s,[^=]*$,$name," $dotfiles_root/symlinks/gitconfig.symlink
sed -i "" -e "5s,[^=]*$,$email," $dotfiles_root/symlinks/gitconfig.symlink

print_success "Added name and email address to your global git config"

# [4] Source bash_profile
source $HOME/.bash_profile

printf "\n"
printf "\r$green All installed$color_off\n"
printf "\n"
